apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-express-deployment
  labels:
    app: nodejs-express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-express
  template:
    metadata:
      labels:
        app: nodejs-express
    spec:
      containers:
        - name: nodejs-express-container
          image: longtranv/hephanbo-thuc-hanh:latest
          ports:
            - containerPort: 3000
        - env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MONGODB_URL
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JWT_SECRET

      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
