apiVersion: v1
kind: Service
metadata:
  name: nodejs-express-service
spec:
  selector:
    app: nodejs-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
